In [44]:
# Create an interactive plot with simple linear model

import pandas as pd

df = pd.read_csv("resources/gdp-vs-happiness.csv")

df.head()

,Entity,Code,Year,GDP per capita (constant 2011 international $),Life satisfaction (country average; 0-10) (Cantril Ladder (0=worst; 10=best)),Unnamed: 5
0,Afghanistan,AFG,1800,NaN,NaN,3280000.0
1,Afghanistan,AFG,1801,NaN,NaN,3280000.0
2,Afghanistan,AFG,1802,NaN,NaN,3280000.0
3,Afghanistan,AFG,1803,NaN,NaN,3280000.0
4,Afghanistan,AFG,1804,NaN,NaN,3280000.0

In [61]:
%config IPCompleter.greedy=True

df[(df['GDP per capita (constant 2011 international $)'].notna()) & \
   (df['Year'] == 2017)]

,Entity,Code,Year,GDP per capita (constant 2011 international $),Life satisfaction (country average; 0-10) (Cantril Ladder (0=worst; 10=best)),Unnamed: 5
217,Afghanistan,AFG,2017,1803.987487,2.661718,3.629600e+07
559,Albania,ALB,2017,11803.430594,4.639548,2.884000e+06
779,Algeria,DZA,2017,13913.839363,5.248912,4.138900e+07
1289,Angola,AGO,2017,5819.494971,NaN,2.981700e+07
1579,Antigua and Barbuda,ATG,2017,21490.942659,NaN,9.500000e+04
...,...,...,...,...,...,...
46506,Vanuatu,VUT,2017,2921.908676,NaN,2.850000e+05
47166,Vietnam,VNM,2017,6171.884192,5.175279,9.460100e+07
47457,World,OWID_WRL,2017,15469.207236,NaN,7.547859e+09
47897,Zambia,ZMB,2017,3689.250826,3.932777,1.685400e+07
48117,Zimbabwe,ZWE,2017,1899.774977,3.638300,1.423700e+07

In [73]:
from bokeh.plotting import figure, output_file, show

from bokeh.models import CustomJS, Slider
from bokeh.layouts import row, column

df_filtered = \
    df[(df['Year'] == 2017) & \
       (df['GDP per capita (constant 2011 international $)'].notna()) & \
       (df['Life satisfaction (country average; 0-10) (Cantril Ladder (0=worst; 10=best))'].notna())
      ]

output_file('resources/gdp-vs-happiness.html')

p = figure(plot_width=800, plot_height=800)


x = df_filtered['GDP per capita (constant 2011 international $)'].tolist()

y = df_filtered['Life satisfaction (country average; 0-10) (Cantril Ladder (0=worst; 10=best))'].tolist()